# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import gfssi_pb2 as gfssi__pb2


class DownLoadStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.DownloadAreaData = channel.unary_unary(
        '/gfssi.DownLoad/DownloadAreaData',
        request_serializer=gfssi__pb2.DownLoadAreaDataRequest.SerializeToString,
        response_deserializer=gfssi__pb2.DownLoadAreaDataResponse.FromString,
        )


class DownLoadServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def DownloadAreaData(self, request, context):
    """Sends a greeting
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DownLoadServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'DownloadAreaData': grpc.unary_unary_rpc_method_handler(
          servicer.DownloadAreaData,
          request_deserializer=gfssi__pb2.DownLoadAreaDataRequest.FromString,
          response_serializer=gfssi__pb2.DownLoadAreaDataResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'gfssi.DownLoad', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
