# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gfssi.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gfssi.proto',
  package='gfssi',
  syntax='proto3',
  serialized_options=_b('\n\026io.grpc.examples.gfssiB\nGFSSIProtoP\001\242\002\003RTG'),
  serialized_pb=_b('\n\x0bgfssi.proto\x12\x05gfssi\"\xd7\x01\n\x17\x44ownLoadAreaDataRequest\x12\x12\n\ndate_start\x18\x01 \x01(\t\x12\x10\n\x08\x64\x61te_end\x18\x02 \x01(\t\x12\x13\n\x0bleft_up_lon\x18\x03 \x01(\x02\x12\x13\n\x0bleft_up_lat\x18\x04 \x01(\x02\x12\x16\n\x0eright_down_lon\x18\x05 \x01(\x02\x12\x16\n\x0eright_down_lat\x18\x06 \x01(\x02\x12\x11\n\tfrequency\x18\x07 \x01(\t\x12\x17\n\x0fresolution_type\x18\x08 \x01(\t\x12\x10\n\x08resultid\x18\t \x01(\t\":\n\x18\x44ownLoadAreaDataResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x10\n\x08zip_file\x18\x02 \x01(\t2a\n\x08\x44ownLoad\x12U\n\x10\x44ownloadAreaData\x12\x1e.gfssi.DownLoadAreaDataRequest\x1a\x1f.gfssi.DownLoadAreaDataResponse\"\x00\x42,\n\x16io.grpc.examples.gfssiB\nGFSSIProtoP\x01\xa2\x02\x03RTGb\x06proto3')
)




_DOWNLOADAREADATAREQUEST = _descriptor.Descriptor(
  name='DownLoadAreaDataRequest',
  full_name='gfssi.DownLoadAreaDataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='date_start', full_name='gfssi.DownLoadAreaDataRequest.date_start', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='date_end', full_name='gfssi.DownLoadAreaDataRequest.date_end', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='left_up_lon', full_name='gfssi.DownLoadAreaDataRequest.left_up_lon', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='left_up_lat', full_name='gfssi.DownLoadAreaDataRequest.left_up_lat', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='right_down_lon', full_name='gfssi.DownLoadAreaDataRequest.right_down_lon', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='right_down_lat', full_name='gfssi.DownLoadAreaDataRequest.right_down_lat', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='frequency', full_name='gfssi.DownLoadAreaDataRequest.frequency', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='resolution_type', full_name='gfssi.DownLoadAreaDataRequest.resolution_type', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='resultid', full_name='gfssi.DownLoadAreaDataRequest.resultid', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=238,
)


_DOWNLOADAREADATARESPONSE = _descriptor.Descriptor(
  name='DownLoadAreaDataResponse',
  full_name='gfssi.DownLoadAreaDataResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='gfssi.DownLoadAreaDataResponse.code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='zip_file', full_name='gfssi.DownLoadAreaDataResponse.zip_file', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=240,
  serialized_end=298,
)

DESCRIPTOR.message_types_by_name['DownLoadAreaDataRequest'] = _DOWNLOADAREADATAREQUEST
DESCRIPTOR.message_types_by_name['DownLoadAreaDataResponse'] = _DOWNLOADAREADATARESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DownLoadAreaDataRequest = _reflection.GeneratedProtocolMessageType('DownLoadAreaDataRequest', (_message.Message,), dict(
  DESCRIPTOR = _DOWNLOADAREADATAREQUEST,
  __module__ = 'gfssi_pb2'
  # @@protoc_insertion_point(class_scope:gfssi.DownLoadAreaDataRequest)
  ))
_sym_db.RegisterMessage(DownLoadAreaDataRequest)

DownLoadAreaDataResponse = _reflection.GeneratedProtocolMessageType('DownLoadAreaDataResponse', (_message.Message,), dict(
  DESCRIPTOR = _DOWNLOADAREADATARESPONSE,
  __module__ = 'gfssi_pb2'
  # @@protoc_insertion_point(class_scope:gfssi.DownLoadAreaDataResponse)
  ))
_sym_db.RegisterMessage(DownLoadAreaDataResponse)


DESCRIPTOR._options = None

_DOWNLOAD = _descriptor.ServiceDescriptor(
  name='DownLoad',
  full_name='gfssi.DownLoad',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=300,
  serialized_end=397,
  methods=[
  _descriptor.MethodDescriptor(
    name='DownloadAreaData',
    full_name='gfssi.DownLoad.DownloadAreaData',
    index=0,
    containing_service=None,
    input_type=_DOWNLOADAREADATAREQUEST,
    output_type=_DOWNLOADAREADATARESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DOWNLOAD)

DESCRIPTOR.services_by_name['DownLoad'] = _DOWNLOAD

# @@protoc_insertion_point(module_scope)
